FROM node:14.15.1-alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


# add `/usr/src/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package*.json /usr/src/app/

#skip building dtrace provider
ENV NODE_DTRACE_PROVIDER_REQUIRE hard

RUN npm install

RUN npm i -g --no-optional pm2

COPY ./server /usr/src/app/server
COPY ./services /usr/src/app/services
COPY ./lib /usr/src/app/lib
COPY ./.babelrc /usr/src/app/.babelrc
COPY ./.env /usr/src/app/.env

# start app
CMD ["npm", "run", "start-prod"]